### ISSUE TITLE
Home Assistant example in readme.md

### ISSUE THREAD

**Issue by KjellRanda** [gmeks/myUplinkSmartConnect#10]
In the Home Assistant integration example in readme.md following mqtt sensor is defined

    - name: "Energi in tank"
      state_topic: "heater/18760NE2240322014631/EnergiStored"
      unique_id: "Waterheater.EnergiStored"
      device_class: power
      unit_of_measurement : kWh 

This result in the following warning in HA:
023-03-27 16:38:45.172 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.energi_in_tank (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'kWh' which is not a valid unit for the device class ('power') it is using; expected one of ['W', 'kW']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

This is caused by
      device_class: power
      unit_of_measurement : kWh 
as this is energy and not power. Chanhing to
      device_class: energy
      unit_of_measurement : kWh 
seems to fix the issue

**Comment by gmeks** [comment]
Should be fixed now
