### ISSUE TITLE
Four minor issues 

### ISSUE THREAD

**Issue by KjellRanda** [gmeks/myUplinkSmartConnect#5]
Have been using the program for a while now and it seems to work great.

I have identified 4 minor issues that you might want to correct.

When the daily scedule is running I find the following in the log file:
...
[16:17:25 WRN] Failed to find tekniskal name of powerzone from fr
[16:17:25 WRN] Failed to find tekniskal name of powerzone from nl
Is tekniskal a misspelling for technical?

When the schedule was running today 20.02.2023 I find teh following in the log
[16:17:29 DBG] Schedule update was successfull next one will be 02/20/2023 15:17:00
Shoud not next one be on 02/21/2023 instead of 02/20/2023

Looking at the code I see the following in myUplinkSmartConnect/xElectricityPriceApiShared/ElectricityPrice/Nordpoolgroup.cs
Line 61: _logger.LogInformation($"Login to myUplink API failed with status {tResponse.StatusCode} and message {tResponse.Content}");
Line 100:  _logger.LogInformation($"Login to myUplink API failed with status {tResponse.StatusCode} and message {tResponse.Content}");
As I read and undestand the code these are not the correct messages to log here. Perhaps cut and paste from other file and not changed.

**Comment by gmeks** [comment]
Yea the log is mostly debug thats should not be warning, il set it to debug.  Its there basicly if nordpool where to change their json format.

The other one is simply wrong, the code  checks timedifference, so your correct the log is wrong.

**Comment by KjellRanda** [comment]
Have been running this for a  week now and is seems to work just fine
